name: homelab

services:
  traefik:
    image: traefik:v2.11
    container_name: traefik
    restart: unless-stopped
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./core/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./core/traefik/dynamic:/etc/traefik/dynamic:ro
      - ./core/traefik/certs:/certs:ro
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    labels:
      - traefik.enable=true

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CF_TUNNEL_TOKEN}
    networks:
      - proxy
    volumes:
      - ../logs/cloudflared:/var/log/cloudflared

  website:
    image: nginx:alpine
    container_name: website
    restart: unless-stopped
    volumes:
      - ./sites/website/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sites/website/html:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.website.rule=Host(`${WEBSITE_HOST}`)
      - traefik.http.routers.website.entrypoints=websecure
      - traefik.http.routers.website.tls=true
      - traefik.http.routers.website.middlewares=default-chain@file
      - traefik.http.services.website.loadbalancer.server.port=80

  test-site:
    image: nginx:alpine
    container_name: test-site
    restart: unless-stopped
    volumes:
      - ./sites/test-site/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./sites/test-site/html:/usr/share/nginx/html:ro
    networks:
      - proxy
    labels:
      - traefik.enable=true
      - traefik.http.routers.test-site.rule=Host(`${TEST_SITE_HOST}`)
      - traefik.http.routers.test-site.entrypoints=websecure
      - traefik.http.routers.test-site.tls=true
      - traefik.http.routers.test-site.middlewares=default-chain@file
      - traefik.http.services.test-site.loadbalancer.server.port=80

networks:
  proxy:
    name: proxy
    driver: bridge
